### ISSUE TITLE
Stream closed

### ISSUE THREAD

**Issue by blutorange** [blutorange/closure-compiler-maven-plugin#44]
Happens only during m2e incremental build (WIndows)
```
java.io.IOException: Stream Closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.FilterOutputStream.close(Unknown Source)
	at org.eclipse.m2e.core.internal.builder.plexusbuildapi.ChangedFileOutputStream.close(ChangedFileOutputStream.java:65)
	at com.github.blutorange.maven.plugin.closurecompiler.plugin.ProcessJSFilesTask.minify(ProcessJSFilesTask.java:144)
	at com.github.blutorange.maven.plugin.closurecompiler.plugin.ProcessFilesTask.processFiles(ProcessFilesTask.java:245)
	at com.github.blutorange.maven.plugin.closurecompiler.plugin.ProcessFilesTask.call(ProcessFilesTask.java:190)
	at com.github.blutorange.maven.plugin.closurecompiler.plugin.MinifyMojo.execute(MinifyMojo.java:652)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by blutorange** [comment]
```xml
				<groupId>com.github.blutorange</groupId>
				<artifactId>closure-compiler-maven-plugin</artifactId>
				<configuration>
					<charset>UTF-8</charset>
					<closureWarningLevels>
						<misplacedTypeAnnotation>OFF</misplacedTypeAnnotation>
						<es5Strict>OFF</es5Strict>
						<unknownDefines>OFF</unknownDefines>
						<nonStandardJsDocs>OFF</nonStandardJsDocs>
						<uselessCode>OFF</uselessCode>
					</closureWarningLevels>
					<closurePrettyPrint>${is-dev-build}</closurePrettyPrint>
					<closureIncludeSourcesContent>true</closureIncludeSourcesContent>
					<closureSourceMapOutputType>inline</closureSourceMapOutputType>
					<closureCreateSourceMap>${is-dev-build}</closureCreateSourceMap>
					<closureDebug>${is-dev-build}</closureDebug>
					<closureLanguageIn>ECMASCRIPT_2016</closureLanguageIn>
					<closureLanguageOut>ECMASCRIPT5</closureLanguageOut>
					<baseSourceDir>${basedir}/src/main</baseSourceDir>
					<baseTargetDir>${project.build.directory}/generated-resources/META-INF/resources/despina</baseTargetDir>

					<execution>
						<id>minify-locale</id>
						<phase>generate-resources</phase>
						<configuration>
							<skipMinify>true</skipMinify>
							<skipMerge>false</skipMerge>
							<sourceDir>js/locale</sourceDir>
							<targetDir>js</targetDir>
							<outputFilename>locale.js</outputFilename>
							<includes>
								<include>*.js</include>
							</includes>
						</configuration>
						<goals>
							<goal>minify</goal>
						</goals>
					</execution>

```

**Comment by blutorange** [comment]
a9ed21a0bc431735e70f5845c60f1a0eb475b781 and 5d89bf983c9f8c83cba0f02c132bbcb38833f7b5 should fix this issue.
